
//! THIS FILE IS AUTO GENERATED BY https://inlang.dev
//! Do not modify by hand.
//
//
// This file exports the following variables
//      'translations': contains the translations
//      'inlangConfig': contains the configuration for inlang
//
// Futhermore, a 't()' function is exported which can be
// invoked to translate given text e.g.
//      t("Hello World") -> "Hallo Welt"

import { Inlang } from 'inlang';

/**
 * Contains translations.
 */
export const translations = {};

/**
 * Use for fine grained inlang setup.
 *
 * If you don't need fine granined setup, use the provided t() function.
 */
export const inlangConfig = {
  "projectId": "7ce04ba0-4e49-4d43-a2bd-0041933d584c",
  "locales": [
    "de",
    "es",
    "fr",
    "nl"
  ],
  "defaultLocale": "en"
};

/**
 * Private inlang object used for the t() function. 
 */
let inlang;

export function setLocale(locale){
	if (inlang === undefined) {
		inlang = new Inlang({
			projectConfig: inlangConfig,
			translations: translations,
			locale: locale
		});
	} else {
		inlang.locale = locale
	}
}

/**
 * Auto-configuration inlang object which can be used directly to translate text.
 *
 * Use 'setLocale()' to set the locale which t() uses. 
 *
 * @returns translated text (if exists)
 */
export function t(text, args) {
	if (inlang === undefined) {
		inlang = new Inlang({
			projectConfig: inlangConfig,
			translations: translations,
			locale: inlangConfig.defaultLocale
		});
	}
	return inlang.translate(text, args);
}
