import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { t } from "../translations";

export default function Home() {
  // using the router to get the current locale of the website
  // https://nextjs.org/docs/advanced-features/i18n-routing
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>{t("Create Next App")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ position: "absolute", left: "10rem", top: "1rem" }}>
        <label name="language">{t("language")}</label>
        <select
          name="language"
          value={router.locale}
          onChange={async (event) => {
            // pushing the new route with the selected locale
            await router.push("/", "/", { locale: event.target.value });
            // reloading the site, otherwise the text is not re-rendered
            // and therefore does not reflect the change in locale
            await router.reload(`/`);
          }}
        >
          {router.locales.map((locale) => (
            <option key={locale} value={locale}>
              {locale}
            </option>
          ))}
        </select>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("Welcome to Next.js!")}</h1>

        <p className={styles.description}>
          {t("Get started by editing")}{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>{t("Documentation")} &rarr;</h2>
            <p>
              {t("Find in-depth information about Next.js features and API.")}
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>{t("Learn")} &rarr;</h2>
            <p>
              {t("Learn about Next.js in an interactive course with quizzes!")}
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>{t("Examples")} &rarr;</h2>
            <p>
              {t("Discover and deploy boilerplate example Next.js projects.")}
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>{t("Deploy")} &rarr;</h2>
            <p>
              {t(
                "Instantly deploy your Next.js site to a public URL with Vercel."
              )}
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {t("Powered by")}{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
